Hometask1
Vladislavovna2407/AppReact pull request #1
Opened 2023-11-21 13:33 UTC by Vladislavovna2407

2023-11-21 13:34 UTC, Vladislavovna2407 commented
Hometask1

2023-11-21 16:09 UTC, JuliaShurmei requested changes

2023-11-21 16:09 UTC, JuliaShurmei commented on src/App.jsx
> +  /*const [count, setCount] = useState(0)
удали, плиз, не нужные комменты. Их лучше удалять перед пушем

2023-11-21 16:09 UTC, JuliaShurmei commented on src/screens/Login/index.jsx
> +    <form>
попробуй добавить хук useState, чтобы следить за состоянием инпутов

2023-11-22 16:20 UTC, tagizade-samir approved these changes

2023-11-22 16:28 UTC, JuliaShurmei approved these changes

2023-11-23 18:52 UTC, merged